"""rename codigo to code and cantidad to stock in products

Revision ID: 0c1da7145d40
Revises: 20ffe7fa9926
Create Date: 2025-05-02 13:00:59.514915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c1da7145d40'
down_revision: Union[str, None] = '20ffe7fa9926'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('code', sa.String(length=100), nullable=False))
    op.add_column('products', sa.Column('stock', sa.Integer(), nullable=False))
    op.drop_constraint('products_codigo_key', 'products', type_='unique')
    op.create_unique_constraint(None, 'products', ['code'])
    op.drop_column('products', 'codigo')
    op.drop_column('products', 'cantidad')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('cantidad', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('codigo', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'products', type_='unique')
    op.create_unique_constraint('products_codigo_key', 'products', ['codigo'])
    op.drop_column('products', 'stock')
    op.drop_column('products', 'code')
    # ### end Alembic commands ###
