"""update products

Revision ID: 20ffe7fa9926
Revises: cf30286dcac4
Create Date: 2025-04-27 16:37:26.859820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20ffe7fa9926'
down_revision: Union[str, None] = 'cf30286dcac4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('codigo', sa.String(length=100), nullable=False))
    op.add_column('products', sa.Column('cantidad', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('photo', sa.String(length=255), nullable=True))
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.create_unique_constraint(None, 'products', ['codigo'])
    op.drop_column('products', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'products', type_='unique')
    op.alter_column('products', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('products', 'photo')
    op.drop_column('products', 'cantidad')
    op.drop_column('products', 'codigo')
    # ### end Alembic commands ###
